# Generated by Django 4.0.2 on 2022-03-17 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_puublish_date_post_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 17, 13, 14, 30, 780290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 13, 14, 30, 780290, tzinfo=utc)),
        ),
    ]
